server:
  port: 8081

#激活对应的配置环境
spring:
  profiles:
    active: dev

dag.name: bigdogdog

person:
  lastName: 吴福强-${random.uuid}
  age: ${random.int(1,120)}
  boss: false
  birth: 2019/10/10
  maps:
    mapk1: mapv1
    mapk2: mapv2
  lists:
    - list1
    - list2
    - list3
  dog:
    name: ${dog.name:小花狗}
    age: 2

logging:
  level:
    com:
      wufuqiang: trace

---
server:
  port: 8083

spring:
  profiles: dev

